export const SERVER = "http://localhost:3000"

//AUTH
export const SET_SELF = "SET_SELF"
export const SET_USER = "SET_USER"

//CONNECTION
export const CONNECT_SOCKET = 'CONNECT_SOCKET'

//PROFILE
export const UPDATE_SELF = "UPDATE_SELF"
export const RESOLVE_UPDATE_SELF = "RESOLVE_UPDATE_SELF"
export const UPDATE_USER = "UPDATE_USER"

//NETWORK
export const ADD_TO_NETWORK = "ADD_TO_NETWORK"
export const REMOVE_FROM_NETWORK = "REMOVE_FROM_NETWORK"
export const UPDATE_RANGE = "UPDATE_RANGE"

//CONTACTS
export const ADD_CONTACT = "ADD_CONTACT "
export const REMOVE_CONTACT = "REMOVE_CONTACT"

//SETTINGS
export const CHANGE_DISCOVERABLE = "CHANGE_DISCOVERY"
export const RESOLVE_CHANGE_DISCOVERABLE = "RESOLVE_CHANGE_DISCOVERY"
export const BLOCK_USER = "BLOCK_USER"
export const RESOLVE_BLOCK_USER = "RESOLVE_BLOCK_USER"
export const UNBLOCK_USER = "UNBLOCK_USER"
export const RESOLVE_UNBLOCK_USER = "RESOLVE_UNBLOCK_USER"
export const BLOCKED = "BLOCKBLOCKED_USER"
export const LOGOUT = "LOGOUT"
export const RESOLVE_LOGOUT = "RESOLVE_LOGOUT"

//INDICATORS
export const SHOW_SPINNER = "SHOW_SPINNER"
export const SHOW_TOAST = "SHOW_TOAST"