export const SERVER = "http://localhost:3000"
// export const SERVER = "https://nety-development.herokuapp.com"

//AUTH
export const SET_SELF = "SET_SELF"

//CONNECTION
export const CONNECT_SOCKET = 'CONNECT_SOCKET'

//PROFILE
export const UPDATE_SELF = "UPDATE_SELF"
export const RESOLVE_UPDATE_SELF = "RESOLVE_UPDATE_SELF"
export const UPDATE_USER = "UPDATE_USER"

//NETWORK
export const GET_NETWORK = "GET_NETWORK"
export const RESOLVE_GET_NETWORK = "RESOLVE_GET_NETWORK"
export const UPDATE_LOCATION = "UPDATE_LOCATION"
export const ADD_TO_NETWORK = "ADD_TO_NETWORK"
export const REMOVE_FROM_NETWORK = "REMOVE_FROM_NETWORK"
export const UPDATE_RANGE = "UPDATE_RANGE"

//CONTACTS
export const ADD_CONTACT = "ADD_CONTACT"
export const REMOVE_CONTACT = "REMOVE_CONTACT"

//CHATS
export const GET_CHATROOMS = "GET_CHATROOMS"
export const RESOLVE_GET_CHATROOMS = "RESOLVE_GET_CHATROOMS"
export const REMOVE_CHATROOM = "REMOVE_CHATROOM"
export const RESOLVE_REMOVE_CHATROOM = "RESOLVE_REMOVE_CHATROOM"

//MESSAAGES
export const GET_MESSAGES = "GET_MESSAGES"
export const RESOLVE_GET_MESSAGES = "RESOLVE_GET_MESSAGES"
export const SEND_MESSAGE = "SEND_MESSAGE"
export const RESOLVE_SEND_MESSAGE = "RESOLVE_SEND_MESSAGE"
export const GOT_MESSAGE = "GOT_MESSAGE"

//SETTINGS
export const CHANGE_DISCOVERABLE = "CHANGE_DISCOVERY"
export const RESOLVE_CHANGE_DISCOVERABLE = "RESOLVE_CHANGE_DISCOVERY"
export const BLOCK_USER = "BLOCK_USER"
export const RESOLVE_BLOCK_USER = "RESOLVE_BLOCK_USER"
export const UNBLOCK_USER = "UNBLOCK_USER"
export const RESOLVE_UNBLOCK_USER = "RESOLVE_UNBLOCK_USER"
export const BLOCKED = "BLOCKBLOCKED_USER"
export const LOGOUT = "LOGOUT"
export const RESOLVE_LOGOUT = "RESOLVE_LOGOUT"

//INDICATORS
export const SHOW_SPINNER = "SHOW_SPINNER"
export const SHOW_TOAST = "SHOW_TOAST"